logs api: compress encoded_length's zero value to 0x00
There was a bug in Chrome where the client was unable to JSON decode
dozer's /api/logs response for a particular request. The response
contained 1_102_908 logs. Chrome's error message:

	SyntaxError: Unexpected end of JSON input

However

	1. Issuing the request in curl produced the correct result
	2. Issuing the request in Safari produced the correct result.
	3. Issuing the request in Chrome to the old indexer
	   produced the correct result.
	4. Limiting the dozer response to 1_100_000 logs produced the
	   correct result in Chrome.

I started to diagnose the problem from the browser. I attempted to
take the data from response.arrayBuffer() for manual inspection. I ran
into an error when attempting to manually utf-8 decode the buffer:

	RangeError: Invalid typed array length: XXX
		at new Uint8Array (<anonymous>)
		at <anonymous>:1:11
I then recalled that the dozer API returned:

	0x0000000000000000000000000000000000000000000000000000000000000000

instead of

	0x00

for a "zero" enocded_lengths value.

It seems that these extra bytes were pushing Chrome's array limits. I
changed the API to return 0x00 for the zero encoded_length and Chrome
was able to produce the correct result.